### ISSUE TITLE
Promise callback opportunity

### ISSUE THREAD

**Issue by singno** [freshOS/then#11]
Callback will never be called:
![image](https://cloud.githubusercontent.com/assets/5654690/19775149/0d821390-9ca2-11e6-97c5-5c29c601066c.png)

Callback will be called if write "then" logic:
![image](https://cloud.githubusercontent.com/assets/5654690/19775237/5d494d12-9ca2-11e6-8bb6-63c818dbfc1e.png)

Compare with javascript (Callback will run at once while creating a promise):
![image](https://cloud.githubusercontent.com/assets/5654690/19775353/bbba754c-9ca2-11e6-96fe-fc6da23bb155.png)

Okay, which is better one?

**Comment by s4cha** [comment]
@singno  
Thanks a lot for pointing this out.
Indeed ou implementation differ slightly on purpose. We had cases where we needed to store promises without starting them (passing around http calls) and that's why our Promises don't start until a then block is called.
 This is something that might change in the future but is tricky to change since libraries like https://github.com/freshOS/ws rely on this very feature :)
Please excuse the late reply ;)

**Comment by s4cha** [comment]
A line has been added to the readme to explain why that is :)
